# Generated by Django 5.2.17 on 2026-08-04 17:17

import apps.common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, default='#C8A951', max_length=9)),
            ],
            options={
                'verbose_name_plural': 'gallery categories',
                'ordering': ('order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('welcome_message', models.TextField(blank=True, help_text='Shown at the top of the client gallery page.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.gallery_cover_path)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to share'), ('delivered', 'Delivered'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private (client login only)'), ('code', 'Shareable link + access code'), ('public', 'Public link')], default='private', max_length=20)),
                ('access_code', models.CharField(blank=True, db_index=True, help_text='Required when the gallery is shared by link.', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('allow_downloads', models.BooleanField(default=True)),
                ('allow_bulk_download', models.BooleanField(default=True)),
                ('allow_selection', models.BooleanField(default=True)),
                ('allow_favorites', models.BooleanField(default=True)),
                ('selection_limit', models.PositiveIntegerField(default=0, help_text='Maximum photos the client may select. 0 means unlimited.')),
                ('selection_deadline', models.DateField(blank=True, null=True)),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, default='LUMINA ATELIER', max_length=80)),
                ('notify_customer', models.BooleanField(default=True, help_text='Email the client when this gallery is delivered.')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_galleries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='customers.customer')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to='customers.photographer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to='galleries.gallerycategory')),
            ],
            options={
                'verbose_name_plural': 'galleries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to=apps.common.utils.gallery_image_path)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('filename', models.CharField(blank=True, max_length=220)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('is_highlight', models.BooleanField(default=False)),
                ('allow_download', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='galleries.gallery')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('download_type', models.CharField(choices=[('single', 'Single image'), ('bulk', 'Bulk archive')], default='single', max_length=12)),
                ('item_count', models.PositiveIntegerField(default=1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='customers.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='galleries.gallery')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='galleries.galleryimage')),
            ],
            options={
                'verbose_name_plural': 'download history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GalleryAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('view', 'Viewed gallery'), ('unlock_ok', 'Unlocked with code'), ('unlock_fail', 'Wrong access code'), ('download', 'Downloaded'), ('select', 'Changed selection'), ('submit', 'Submitted selection'), ('denied', 'Access denied'), ('expired', 'Expired gallery')], db_index=True, default='view', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='galleries.gallery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['gallery', '-created_at'], name='galleries_g_gallery_3b7b62_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['status', '-created_at'], name='galleries_g_status_19d8cc_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['customer', 'status'], name='galleries_g_custome_5c2550_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['expires_at'], name='galleries_g_expires_d028cf_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['gallery', 'order'], name='galleries_g_gallery_dad88e_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['gallery', '-created_at'], name='galleries_d_gallery_4b8550_idx'),
        ),
    ]
