# Generated by Django 5.2.17 on 2026-08-04 17:17

import apps.common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(blank=True, default='Photographer', max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.CharField(blank=True, help_text='Comma separated, e.g. Weddings, Editorial, Fine Art', max_length=240)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.avatar_path)),
                ('is_lead', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'photographer',
                'verbose_name_plural': 'photographers',
                'ordering': ('order', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=160)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('couple', 'Couple'), ('family', 'Family'), ('corporate', 'Corporate'), ('brand', 'Brand')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('tags', models.CharField(blank=True, help_text='Comma separated labels', max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.photographer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='customers_c_status_b0ea05_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx')],
            },
        ),
    ]
