# Generated by Django 5.2.17 on 2026-08-04 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('album_type', models.CharField(choices=[('fine_art', 'Fine art album'), ('layflat', 'Layflat album'), ('storybook', 'Storybook'), ('print_box', 'Print box'), ('digital', 'Digital delivery only')], default='fine_art', max_length=20)),
                ('size', models.CharField(blank=True, default='30x30 cm', max_length=60)),
                ('cover_material', models.CharField(blank=True, default='Linen', max_length=80)),
                ('page_count', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True, help_text='Client instructions for the studio.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('approved', 'Approved'), ('in_production', 'In production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_requests', to='customers.customer')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_requests', to='galleries.gallery')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlbumSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_selected', models.BooleanField(db_index=True, default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('album_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='albums.albumrequest')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='customers.customer')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='galleries.gallery')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='galleries.galleryimage')),
            ],
            options={
                'ordering': ('sequence', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='albumrequest',
            index=models.Index(fields=['status', '-created_at'], name='albums_albu_status_06f5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='albumrequest',
            index=models.Index(fields=['customer', 'status'], name='albums_albu_custome_7444d8_idx'),
        ),
        migrations.AddIndex(
            model_name='albumselection',
            index=models.Index(fields=['gallery', 'is_selected'], name='albums_albu_gallery_8f44ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='albumselection',
            constraint=models.UniqueConstraint(fields=('gallery', 'image', 'customer'), name='unique_selection_per_customer_image'),
        ),
    ]
