# Generated by Django 5.2.17 on 2026-08-04 17:17

import apps.common.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('title', models.CharField(max_length=160, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=320)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='camera', help_text='Icon key rendered by the front-end (camera, ring, building, film...)', max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.service_image_path)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='EUR', max_length=6)),
                ('price_unit', models.CharField(blank=True, default='per project', max_length=60)),
                ('duration', models.CharField(blank=True, help_text='e.g. Full day / 6 hours', max_length=80)),
                ('turnaround', models.CharField(blank=True, help_text='e.g. 3 weeks', max_length=80)),
                ('features', models.TextField(blank=True, help_text='One feature per line - rendered as a checklist.')),
                ('deliverables', models.TextField(blank=True, help_text='One deliverable per line.')),
                ('cta_label', models.CharField(blank=True, default='Enquire', max_length=60)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ('order', 'title'),
                'abstract': False,
            },
        ),
    ]
