# Generated by Django 5.2.17 on 2026-08-04 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('logout', 'Signed out'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('upload', 'Uploaded images'), ('download', 'Downloaded'), ('selection', 'Selection changed'), ('submit', 'Selection submitted'), ('message', 'Enquiry received'), ('settings', 'Settings changed')], db_index=True, default='update', max_length=24)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activity log',
                'verbose_name_plural': 'activity log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='analytics_a_created_b5efc6_idx'), models.Index(fields=['action', '-created_at'], name='analytics_a_action_8c93de_idx')],
            },
        ),
    ]
